---
# file: roles/application/tasks/database.yml
- name: setup pg database
  sudo: true
  sudo_user: postgres
  postgresql_db:
    name: "{{ database_name }}"
  tags:
    - app
    - db
    - postgresql

- name: setup pg user
  sudo: true
  sudo_user: postgres
  postgresql_user:
    name: "{{ database_user }}"
    db: "{{ database_name }}"
    password: "{{ database_pass }}"
    priv: ALL
  tags:
    - app
    - db
    - postgresql
